// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: () => __TAURI_INVOKE<string>("ping"),
	getAppInfo: () => typedError<AppInfo, string>(__TAURI_INVOKE("get_app_info")),
	getAsrSidecarStatus: () => typedError<AsrSidecarStatus, string>(__TAURI_INVOKE("get_asr_sidecar_status")),
	startRecording: (title: string) => typedError<number, string>(__TAURI_INVOKE("start_recording", { title })),
	stopRecording: (meetingId: number) => typedError<null, string>(__TAURI_INVOKE("stop_recording", { meetingId })),
	listMeetings: (limit: number, offset: number) => typedError<Meeting[], string>(__TAURI_INVOKE("list_meetings", { limit, offset })),
	getMeeting: (id: number) => typedError<{
	id: number,
	title: string,
	started_at: string,
	ended_at: string | null,
	language_primary: string | null,
	audio_path: string | null,
	participants: string[],
} | null, string>(__TAURI_INVOKE("get_meeting", { id })),
	searchMeetings: (query: string, limit: number) => typedError<TranscriptSearchHit[], string>(__TAURI_INVOKE("search_meetings", { query, limit })),
	getTranscript: (meetingId: number) => typedError<Transcript[], string>(__TAURI_INVOKE("get_transcript", { meetingId })),
	generateSummary: (meetingId: number) => typedError<string, string>(__TAURI_INVOKE("generate_summary", { meetingId })),
	getAvailableModels: () => typedError<ModelDef[], string>(__TAURI_INVOKE("get_available_models")),
};

/* Types */
export type AppInfo = {
	name: string,
	version: string,
	is_recording: boolean,
	sidecar_running: boolean,
	asr_ready: boolean,
	llm_ready: boolean,
};

export type AsrSidecarStatus = {
	url: string,
	running: boolean,
};

export type Meeting = {
	id: number,
	title: string,
	started_at: string,
	ended_at: string | null,
	language_primary: string | null,
	audio_path: string | null,
	participants: string[],
};

/**  Definition of a built-in AI model with all metadata */
export type ModelDef = {
	/**
	 *  Model name in format "family:variant" (e.g., "gemma3:1b")
	 *  This is what's stored in database as model field when provider="builtin-ai"
	 */
	name: string,
	/**  Display name for UI (e.g., "Gemma 3 1B (Fast)") */
	display_name: string,
	/**  GGUF filename on disk (e.g., "gemma-3-1b-it-q4_0.gguf") */
	gguf_file: string,
	/**  Template name for prompt formatting (e.g., "gemma3") */
	template: string,
	/**  Download URL (HuggingFace or other source) */
	download_url: string,
	/**  File size in MiB. The field name is kept for API compatibility. */
	size_mb: number,
	/**
	 *  Context window size in tokens (configurable per model!)
	 *  This is used for chunking in processor.rs
	 */
	context_size: number,
	/**  Model layer count (for GPU offloading calculation) */
	layer_count: number,
	/**  Sampling parameters for this model */
	sampling: SamplingParams,
	/**  Short description for UI */
	description: string,
};

/**  Sampling parameters supported by the built-in AI -> llama-helper pipeline. */
export type SamplingParams = {
	/**  Temperature - 0.0 triggers greedy decoding in llama-helper. */
	temperature: number | null,
	/**  Top-K sampling - limits vocabulary to top K tokens. */
	top_k: number,
	/**  Top-P (nucleus) sampling - cumulative probability threshold. */
	top_p: number | null,
	/**  Presence penalty - discourages reusing tokens that already appeared in the generated output. */
	presence_penalty: number | null,
	/**  Frequency penalty - discourages repeated token frequency in the generated output. */
	frequency_penalty: number | null,
	/**  Repeat penalty - llama.cpp repeat penalty, 1.0 disables it. */
	repeat_penalty: number | null,
	/**  Number of recent generated tokens to apply penalties over, 0 disables penalties. */
	penalty_last_n: number,
	/**  Stop tokens - generation stops when any of these appear in output */
	stop_tokens: string[],
};

export type Transcript = {
	id: number,
	meeting_id: number,
	sequence_id: number,
	start_ms: number,
	end_ms: number,
	text: string,
	rewritten_text: string | null,
	language: string | null,
	speaker_label: string | null,
	confidence: number | null,
	is_partial: boolean,
	created_at: string,
};

export type TranscriptSearchHit = {
	transcript_id: number,
	meeting_id: number,
	sequence_id: number,
	text: string,
	rewritten_text: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

